name: Curious Place
title: Curious Place
description: A place for art & experience that take you to new places, real & imaginary.
tags:
  - blog
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: info@curious.place
disqus_username: disqus_username
